# Generated by Django 6.1.1 on 2026-09-08 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=64, unique=True)),
                ('hms_request_id', models.UUIDField(editable=False, unique=True)),
                ('patient_number', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_date_of_birth', models.DateField()),
                ('test_code', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='ACCEPTED', max_length=30)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('result_value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('reference_range', models.CharField(blank=True, default='', max_length=100)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('performed_by', models.CharField(max_length=200)),
                ('verified_by', models.CharField(blank=True, default='', help_text='Name of the lab supervisor who verified the result.', max_length=200)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lis.laborder')),
            ],
        ),
    ]
